FROM node:20-alpine
WORKDIR /app
COPY package.json ./
COPY tsconfig.json ./
COPY apps/checkout ./apps/checkout
WORKDIR /app/apps/checkout
RUN npm install
EXPOSE 3008
CMD ["npx", "ts-node", "src/index.ts"]