FROM node:20-alpine
WORKDIR /app
COPY package.json ./
COPY tsconfig.json ./
COPY packages/database ./packages/database
COPY apps/order-service ./apps/order-service
WORKDIR /app/apps/order-service
RUN npm install
RUN npx prisma generate --schema=../../packages/database/prisma/schema.prisma
EXPOSE 3002
CMD ["npx", "ts-node", "src/index.ts"]