FROM node:20-alpine
WORKDIR /app
COPY package.json ./
COPY tsconfig.json ./
COPY apps/api-gateway ./apps/api-gateway
WORKDIR /app/apps/api-gateway
RUN npm install
EXPOSE 3000
CMD ["npx", "ts-node", "src/index.ts"]