FROM node:20-alpine
WORKDIR /app
COPY package.json ./
COPY tsconfig.json ./
COPY apps/notification-service ./apps/notification-service
WORKDIR /app/apps/notification-service
RUN npm install
EXPOSE 3007
CMD ["npx", "ts-node", "src/index.ts"]