FROM node:20-alpine
WORKDIR /app
COPY package.json ./
COPY tsconfig.json ./
COPY packages/database ./packages/database
COPY apps/settlement-service ./apps/settlement-service
WORKDIR /app/apps/settlement-service
RUN npm install
RUN npx prisma generate --schema=../../packages/database/prisma/schema.prisma
EXPOSE 3006
CMD ["npx", "ts-node", "src/index.ts"]