FROM node:20-alpine
WORKDIR /app
COPY package.json ./
COPY tsconfig.json ./
COPY packages/database ./packages/database
COPY apps/payment-service ./apps/payment-service
WORKDIR /app/apps/payment-service
RUN npm install
RUN npx prisma generate --schema=../../packages/database/prisma/schema.prisma
EXPOSE 3003
CMD ["npx", "ts-node", "src/index.ts"]